# Generated by Django 6.0.6 on 2026-06-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='course',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='mobile',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
